#!/usr/bin/env bash

workspace=$(printf "Personal\nFinxact\n" | fzf)

if [[ -z "$workspace" ]];then
	exit 0
fi

selected=""
if [[ "$workspace" == "Personal" ]]; then
	selected=$(find $HOME/Projects -mindepth 1 -maxdepth 1 -type d | fzf)
elif [[ "$workspace" == "Finxact" ]]; then
	selected=$(find $HOME/go/src/go.finxact.io/engineering -mindepth 2 -maxdepth 2 -type d | fzf)
fi

if [[ -z "$selected" ]];then
	exit 0
fi

selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	if [[ -z "$TUMX" ]]; then
		tmux attach-session -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t=$selected_name 2> /dev/null; then
	switch_to
	exit 0
fi

tmux new-session -ds $selected_name -c $selected
tmux send-keys -t $selected_name "ready-tmux" ^M
switch_to
